[package]
name = "locale_config"
version = "0.1.1-pre"
description = """
Maintains locale preferences for process and thread and initialises them by
inspecting the system for user preference.
"""
authors = [
    "Jan Hudec <bulb@ucw.cz>",
]
documentation = "https://rust-locale.github.io/locale_config/locale_config/"
repository = "https://github.com/rust-locale/locale_config/"
license = "MIT"

[dependencies]
lazy_static = "0.2"
regex = "0.1"

[package.metadata.release]
upload-doc = true
